### PR TITLE
Fix crash in TaskDelegate

### LINKED ISSUE #1708: Crash in TaskDelegate
Randomly have crashes in TaskDelegate from download task on background session on line 335: 

```
        let result = destination(location, downloadTask.response as! HTTPURLResponse)
```

The download task response is nil that's why it's crashing. Is it normal that there is no safe unwrapping ?

### PR DESCRIPTION
**Pull request by jshier**
This PR fixes #1708 by refactoring logic in `TaskDelegate` to properly check for a nil response.

### CODE REVIEW

File: Source/TaskDelegate.swift [hunk 1]
```diff
@@ -330,30 +330,29 @@ class DownloadTaskDelegate: TaskDelegate, URLSessionDownloadDelegate {
...
-                    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true, attributes: nil)
-                }
-
-                try FileManager.default.moveItem(at: location, to: destination)
-            } catch {
-                self.error = error
+        
+        guard
+            let destination = destination,
+            let response = downloadTask.response as? HTTPURLResponse else { return }
```
Comment (cnoon) [inline Source/TaskDelegate.swift]: Could we pull the `else` down a line?

```swift
guard
    let destination = destination,
    let response = downloadTask.response as? HTTPURLResponse 
else { return }
```

File: Tests/DownloadTests.swift [hunk 2]
```diff
@@ -101,6 +101,34 @@ class DownloadResponseTestCase: BaseTestCase {
...
+        
+        waitForExpectations(timeout: timeout, handler: nil)
+        
+        // Then
+        XCTAssertNotNil(response?.request)
+        XCTAssertNil(response?.response)
+        XCTAssertNil(response?.destinationURL)
+        XCTAssertNil(response?.resumeData)
+        XCTAssertNotNil(response?.error)
+    }
```
Comment (cnoon) [inline Tests/DownloadTests.swift]: Does this reproduce  the crash reported in #1708? Assuming yes, but thought I'd ask just to make sure.

File: Source/TaskDelegate.swift [hunk 3]
```diff
@@ -330,30 +330,29 @@ class DownloadTaskDelegate: TaskDelegate, URLSessionDownloadDelegate {
...
+        
+        let result = destination(location, response)
+        let destinationURL = result.destinationURL
+        self.destinationURL = destinationURL
+        let options = result.options
```
Comment (cnoon) [inline Source/TaskDelegate.swift]: The `destinationURL` assignment is a bit weird tucked in the middle of the other assignments. How about something like this?

```swift
let result = destination(location, response)
let destinationURL = result.destinationURL
let options = result.options

self.destinationURL = destinationURL

do {
```

File: Tests/DownloadTests.swift (hunk 2 above)
Comment (jshier) [inline Tests/DownloadTests.swift]: Turns out it doesn't, as this delegate method doesn't get called with a cancelled download request. I can't find a way to replicate this cause (nil response) in that method. Perhaps it's related to the background session? I can just remove the test and we can land this as a speculative fix if the logic looks good.

Comment (cnoon) [inline Tests/DownloadTests.swift]: I couldn't find a way to repro the crash either. The test is useful though so we just as well keep it. 👍🏼

File: Source/TaskDelegate.swift (hunk 3 above)
Comment (cnoon) [inline Source/TaskDelegate.swift]: I made this change and force pushed.
